import java.io.File

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ksp)
}

// Release signing: keystore + password live OUTSIDE this repo.
// Defaults point at the user-home files generated by the keystore script.
// Override via BASTION_KEYSTORE_PATH / BASTION_KEYSTORE_PASSWORD_FILE env vars
// (e.g. in CI: write the secrets to disk, then export the env vars).
val keystorePath: String = System.getenv("BASTION_KEYSTORE_PATH")
    ?: "${System.getProperty("user.home")}/bastion-mobile-release.keystore"
val keystorePasswordFile: String = System.getenv("BASTION_KEYSTORE_PASSWORD_FILE")
    ?: "${System.getProperty("user.home")}/bastion-mobile-keystore-password.txt"
val keystorePassword: String? = File(keystorePasswordFile)
    .takeIf { it.exists() }
    ?.readText()
    ?.trim()
val releaseSigningAvailable: Boolean = File(keystorePath).exists() && !keystorePassword.isNullOrEmpty()

android {
    namespace = "cam.bastion.mobile"
    compileSdk = 35

    defaultConfig {
        applicationId = "cam.bastion.mobile"
        minSdk = 26
        targetSdk = 35
        versionCode = 11
        versionName = "0.4.0"
        vectorDrawables { useSupportLibrary = true }
    }

    signingConfigs {
        if (releaseSigningAvailable) {
            create("release") {
                storeFile = File(keystorePath)
                storePassword = keystorePassword
                keyAlias = "bastion-release"
                keyPassword = keystorePassword
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (releaseSigningAvailable) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }
    buildFeatures { compose = true }
    packaging {
        resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    debugImplementation(libs.androidx.ui.tooling)

    // v0.4.0 ECHO/SCAN: CameraX for front-cam preview + frame analysis,
    // ML Kit on-device face detection for shadow-scan (shoulder-surfer alert).
    implementation(libs.androidx.camera.core)
    implementation(libs.androidx.camera.camera2)
    implementation(libs.androidx.camera.lifecycle)
    implementation(libs.androidx.camera.view)
    implementation(libs.mlkit.face.detection)
}
